[build]
  CI= "npm run build"
  publish = "dist"
  NODE_ENV = "22.11.0"


[dev]
  CI= "npm run build"


[build.processing.html]
  pretty_urls = true


[[redirects]]
  from = "/assets/img/:file"
  to = "/.netlify/images?url=/assets/img/:file"
  status = 200

[[redirects]]
  from = "assets/img/:width/:file"
  to = "/.netlify/images?url=/assets/img/:file&width=:width"
  status = 200